version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    container_name: app
  redis:
    image: redis:latest
    container_name: cache